version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pidao_db
    networks:
      - pi_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    env_file: ./backend/.env
    depends_on:
      - postgres
    networks:
      - pi_network
    # در اینجا پورت 5000 داخلی است. 
    # اگر بخواهید از بیرون هم به بک دسترسی داشته باشید، می‌توانید مپ کنید:
    # ports:
    #   - "5001:5000" 

  frontend:
    build: ./frontend
    restart: always
    # مپ کردن پورت 5000 داخلی به 3000 خارجی برای تست راحت‌تر در مرورگر
    ports:
      - "3000:5000" 
    networks:
      - pi_network

  reverse-proxy:
    build: ./reverse-proxy
    restart: always
    environment:
      - DOMAIN_NAME=apppidaonkm2562.pinet.com
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - pi_network

networks:
  pi_network:
    driver: bridge

volumes:
  postgres_data:
