version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pidao_db
    networks:
      - pi_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    env_file: ./backend/.env
    depends_on:
      - postgres
    networks:
      - pi_network

  frontend:
    build: ./frontend
    restart: always
    # پورت 3000 را اینجا نگه می‌داریم چون در vite.config تنظیم کردیم
    ports:
      - "3000:3000"
    networks:
      - pi_network

  reverse-proxy:
    build: ./reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=localhost # در حالت عملیاتی آدرس دامنه را اینجا بنویسید
    depends_on:
      - backend
      - frontend
    networks:
      - pi_network

networks:
  pi_network:
    driver: bridge

volumes:
  postgres_data:
