name: Build and Deploy Frontend

on:
  push:
    branches:
      - main  # اگر نام برنچ اصلی شما master است، اینجا را به master تغییر دهید

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json # اگر فایل lock ندارید این خط را حذف کنید

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build project
        run: |
          cd frontend
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist # مشخص می‌کند که فقط محتویات پوشه ساخته شده را منتشر کند
          branch: gh-pages     # یک شاخه جدید به نام gh-pages برای سایت می‌سازد
